# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/raft.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setObjectName("status_label")
        self.verticalLayout.addWidget(self.status_label)
        self.send_widget = QtWidgets.QWidget(self.centralwidget)
        self.send_widget.setObjectName("send_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.send_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.data_line = QtWidgets.QLineEdit(self.send_widget)
        self.data_line.setObjectName("data_line")
        self.horizontalLayout.addWidget(self.data_line)
        self.send_button = QtWidgets.QPushButton(self.send_widget)
        self.send_button.setObjectName("send_button")
        self.horizontalLayout.addWidget(self.send_button)
        self.verticalLayout.addWidget(self.send_widget)
        self.log_view = QtWidgets.QTextEdit(self.centralwidget)
        self.log_view.setReadOnly(True)
        self.log_view.setObjectName("log_view")
        self.verticalLayout.addWidget(self.log_view)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.status_label.setText(_translate("MainWindow", "TextLabel"))
        self.send_button.setText(_translate("MainWindow", "Send!"))
